### ISSUE TITLE
TODO: Documentation

### ISSUE THREAD

**Issue by Megaf** [Megaf/BoxTextLib.sh#4]
Below is things to add to the documentation.
- [x] How to use the lib.
- [x] Information on styles and how to use them.
- [x] Licensing information.
- [x] How to add the lib to ones project.
- [x] Explaining how to replace "echo"/"printf" with `style="stylename" message="message here"`
- [x] More?

**Comment by Megaf** [comment]
Done.
